---  
- name: Check/Apply SNMPv3 Authentication/Encryption Configuration
  cisco.iosxr.iosxr_snmp_server:
      config: "{{ snmp_iosxr }}"
      state: replaced
  register: snmp_diff

- name: Apply snmp auth/encryption passwords
  cisco.iosxr.iosxr_config:
    lines: "snmp-server user V3USER V3GROUP v3 auth sha {{ iosxr_snmp_auth }} priv aes 256 {{ iosxr_snmp_priv }}"

- ansible.builtin.debug:
    msg:
    - "current snmp config"
    - "{{ snmp_diff.before }}"
    - "replace commands (remediation)"
    - "{{ snmp_diff.commands | default ('no diff found') }}"
  ignore_errors: yes
