---
- name: Check/Apply SNMPv3 Authentication/Encryption Configuration
  cisco.nxos.nxos_snmp_server:
      config: "{{ snmp_nxos }}"
      state: replaced
  register: snmp_diff
  notify: SNMP compliance violation

- ansible.builtin.debug:
    msg:
    - "current snmp config"
    - "{{ snmp_diff.before }}"
    - "replace commands (remediation)"
    - "{{ snmp_diff.commands | default ('no diff found') }}"



