---
- name: Compliance Check for Router settings
  hosts: "{{ group }}"
  gather_facts: false
  

  tasks:
    - name: load ntp compliance role
      include_role:
        name: roles/ntp
      when: tag == 'ntp'

    - name: load snmp compliance role
      include_role:
        name: roles/snmp
      when: tag == 'snmp'

    - name: load logging compliance role
      include_role:
        name: roles/logging
      when: tag == 'logging'

    - name: load acl compliance role
      include_role:
        name: roles/acl
      when: tag == 'acl'

    