---
- name: Compliance Check for Router settings
  hosts: "{{ group }}"
  gather_facts: false
  
  tasks:

    - name: Setup initial firewall settings
      ansible.builtin.include_role: 
        name: "roles/{{ item }}"
      loop: "{{ tag }}"
      

    