---
- name: Compliance Check for NTP server settings
  hosts: "{{ group }}"
  gather_facts: false

  tasks:
    - name: load compliance role
      include_role:
        name: ../roles/compliance
      tags: 
      - ntp
      - snmp
      - logging
    