---
#Devnet Always On Sandboxes
ios:
  hosts:
    sandbox-iosxe-recomm-1.cisco.com
    
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: developer
    ansible_password: lastorangerestoreball8876
    ansible_port: 22

iosxr:
  hosts:
    sandbox-iosxr-1.cisco.com
  vars:
    ansible_user: admin
    ansible_password: C1sco12345
    ansible_network_os: cisco.iosxr.iosxr
    ansible_connection: ansible.netcommon.network_cli

nxos:
  hosts:
    sandbox-nxos-1.cisco.com
  vars: 
    ansible_user: admin
    ansible_password: Admin_1234!
    ansible_network_os: cisco.nxos.nxos
    ansible_connection: ansible.netcommon.network_cli

devnet_routers:
  children:
    ios:
    iosxr:
    nxos:
# ansible-dev AAP/AWS
cisco_only:
  hosts:
    rtr1:
      ansible_host: 3.15.71.20
    rtr2:
      ansible_host: 3.21.249.77
    rtr3:
      ansible_host: 3.130.133.107
    rtr4:
      ansible_host: 3.134.226.219
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios

stig_router: 
  hosts:
    stig-rtr:
      ansible_host: 3.128.239.55
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios

#Dcloud
cat:
  hosts:
    198.18.1.31:
    198.18.1.32:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: developer
    ansible_password: 
    
junos:
  hosts: 
    18.220.10.18:
      ansible_user: ec2-user
      ansible_connection: netconf
      ansible_network_os: junos

