---
#Devnet Always On Sandboxes
ios:
  hosts:
    sandbox-iosxe-latest-1.cisco.com
  vars:
    ansible_user: admin
    ansible_password: C1sco12345
    ansible_network_os: ios
    ansible_connection: network_cli
    
iosxr:
  hosts:
    sandbox-iosxr-1.cisco.com
  vars:
    ansible_user: admin
    ansible_password: C1sco12345
    ansible_network_os: iosxr
    ansible_connection: network_cli

nxos:
  hosts:
    sandbox-nxos-1.cisco.com
  vars: 
    ansible_user: admin
    ansible_password: Admin_1234!
    ansible_network_os: nxos
    ansible_connection: network_cli

routers:
  children:
    ios:
    iosxr:
    nxos:


  