# Check ntp servers' IP address before replacing
- name: Check/Replace existing config for compliance
  cisco.nxos.nxos_ntp_global:
    config: "{{ ntp_nxos }}"
    state: replaced
  register: diff
  tags: ntp

- ansible.builtin.debug:
    msg:
    - "current ntp config"
    - "{{ diff.before.servers }}"
    - "replace commands (remediation)"
    - "{{ diff.commands | default ('no diff found') }}"
  tags: ntp
       
- name: Check/Apply SNMPv3 Authentication/Encryption Configuration
  cisco.nxos.nxos_snmp_server:
      config: "{{ snmp_nxos }}"
      state: overridden
  register: snmp_diff
  tags: snmp

- ansible.builtin.debug:
    msg:
    - "current snmp config"
    - "{{ snmp_diff.before }}"
    - "replace commands (remediation)"
    - "{{ snmp_diff.commands | default ('no diff found') }}"
  tags: snmp

- name: Check/Apply NXOS logging configuration
  cisco.nxos.nxos_logging_global:
    config: "{{ logging_nxos }}"   
    state: replaced
  register: logging_diff
  tags: logging

- ansible.builtin.debug:
    msg:
    - "current logging config"
    - "{{ logging_diff.before }}"
    - "replace commands (remediation)"
    - "{{ logging_diff.commands | default ('no diff found') }}"
  tags: logging

  