# Check ntp servers' IP address before replacing
- name: Check/Replace existing NTP for compliance
  cisco.iosxr.iosxr_ntp_global:
    config: "{{ ntp_iosxr }}"
    state: replaced
  check_mode: "{{ check }}"
  register: diff
  tags: ntp

- ansible.builtin.debug:
    msg:
    - "current ntp config"
    - "{{ diff.before }}"
    - "replace commands (remediation)"
    - "{{ diff.commands | default ('no diff found') }}"
  tags: ntp
       
- name: Check/Apply SNMPv3 Authentication/Encryption Configuration
  cisco.iosxr.iosxr_snmp_server:
      config: "{{ snmp_iosxr }}"
      state: replaced
  check_mode: "{{ check }}"
  register: snmp_diff
  tags: snmp
  ignore_errors: yes

- ansible.builtin.debug:
    msg:
    - "current snmp config"
    - "{{ snmp_diff.before }}"
    - "replace commands (remediation)"
    - "{{ snmp_diff.commands | default ('no diff found') }}"
  tags: snmp 
  ignore_errors: yes