---
- name: Check/Apply IOSXE ACLs 
  cisco.ios.ios_acls:
    config: "{{ acls }}"   
    state: replaced
  #check_mode: "{{ check }}"
  register: acls_diff

- ansible.builtin.debug:
    msg:
    - "current acl config"
    - "{{ acls_diff.before }}"
    - "replace commands (remediation)"
    - "{{ acls_diff.commands | default ('no diff found') }}"

- name: Check/Apply IOSXE ACLs Iterfaces
  cisco.ios.ios_acl_interfaces:
    config: "{{ acl_interfaces }}" 
    state: replaced
  #check_mode: "{{ check }}"
  register: acls_int_diff
  notify: ACL compliance violation

- ansible.builtin.debug:
    msg:
    - "current acl config"
    - "{{ acls_int_diff.before }}"
    - "replace commands (remediation)"
    - "{{ acls_int_diff.commands | default ('no diff found') }}"
